### ISSUE TITLE
CustomResourceDefinition "ansibleees.redhat.com" is invalid:

### ISSUE THREAD

**Issue by SeanMooney** [openstack-k8s-operators/openstack-ansibleee-operator#45]
The CustomResourceDefinition "ansibleees.redhat.com" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[extraMounts].items.properties[volumes].items.properties[ephemeral].properties[volumeClaimTemplate].properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set

while its not entirely clear where the issue is i would assume its around here

https://github.com/openstack-k8s-operators/ansibleee-operator/blob/main/config/crd/bases/redhat.com_ansibleees.yaml#L782-L816

this operator does not seam to be following the pattern used in all the other as i would expect
the CRD to be generated programmatically form the type definition here

https://github.com/openstack-k8s-operators/ansibleee-operator/blob/main/api/v1alpha1/ansibleee_types.go#L28-L68

instead the CRD seams to be generated form here
https://github.com/openstack-k8s-operators/ansibleee-operator/blob/main/api/bases/redhat.com_ansibleees.yaml

that likely should be changed to align without all the other operators 

with that said as best i can tell the bug is likely in this file

https://github.com/openstack-k8s-operators/ansibleee-operator/blob/main/api/bases/redhat.com_ansibleees.yaml#L782-L816

summing that the one int he config/crd folder is derived form that.

i think the fix is just to add  x-kubernetes-map-type: atomic

but i do not see a claims key under the resource section

until this is resolved the ansibleee operator will not be deployable.

**Comment by fao89** [comment]
I'm curious why CI didn't catch this

**Comment by jlarriba** [comment]
Was this issue fixed by https://github.com/openstack-k8s-operators/ansibleee-operator/pull/47?

**Comment by SeanMooney** [comment]
yep i forgot to put Closes: in the PR mesagage to get it to auto close
